# Generated by Django 5.0.14 on 2026-09-29 23:44

import django.db.models.deletion
import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[usuarios.validators.validar_rut_chileno], verbose_name='RUT Chileno')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de Domicilio')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('numero_ficha', models.CharField(max_length=20, unique=True, verbose_name='Número de Ficha')),
                ('fecha_apertura', models.DateField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('observaciones_generales', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ficha_clinica', to='fichas.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Ficha Clínica',
                'verbose_name_plural': 'Fichas Clínicas',
            },
        ),
        migrations.CreateModel(
            name='AntecedenteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias Conocidas (Fármacos/Latex)')),
                ('enfermedades_cronicas', models.TextField(blank=True, null=True, verbose_name='Enfermedades Crónicas (Diabetes, Hipertensión, etc.)')),
                ('medicamentos_actuales', models.TextField(blank=True, null=True, verbose_name='Medicamentos en Uso')),
                ('fuma', models.BooleanField(default=False, verbose_name='¿Es Fumador?')),
                ('embarazada', models.BooleanField(default=False, verbose_name='¿Está Embarazada?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_medicos', to='fichas.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Antecedente Médico',
                'verbose_name_plural': 'Antecedentes Médicos',
            },
        ),
    ]
