# Generated by Django 5.0.14 on 2026-10-04 18:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_delete_citamedica'),
        ('fichas', '0001_initial'),
        ('usuarios', '0002_alter_usuario_rol_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaclinica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ficha_clinica', to='usuarios.paciente'),
        ),
        migrations.AlterModelOptions(
            name='fichaclinica',
            options={'verbose_name': 'Ficha clínica', 'verbose_name_plural': 'Fichas clínicas'},
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='fecha_apertura',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='modificado_en',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='numero_ficha',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='observaciones_generales',
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='antecedentes_medicos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('diagnostico', models.TextField(blank=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='atencion', to='citas.cita')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='fichas.fichaclinica')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='fichas.atencion')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='fichas.atencion')),
            ],
        ),
        migrations.DeleteModel(
            name='AntecedenteMedico',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
