# Generated by Django 5.0.14 on 2026-10-04 18:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_cita_delete_citamedica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('medio', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_PRESENCIAL', 'Tarjeta presencial (POS)')], max_length=20)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referencia_pos', models.CharField(blank=True, max_length=50)),
                ('resultado_pos', models.CharField(blank=True, choices=[('APROBADO', 'Aprobado en el POS'), ('RECHAZADO', 'Rechazado en el POS')], max_length=10)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='citas.cita')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='pagos.pago')),
            ],
            options={
                'verbose_name': 'Comprobante de pago',
                'verbose_name_plural': 'Comprobantes de pago',
            },
        ),
    ]
