# Generated by Django 5.0.14 on 2026-09-30 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de Consulta')),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('EN_ATENCION', 'En Atención'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20, verbose_name='Estado de Cita')),
                ('odontologo', models.ForeignKey(limit_choices_to={'rol__nombre': 'Odontologo'}, on_delete=django.db.models.deletion.PROTECT, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='fichas.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
