# Generated by Django 5.0.14 on 2026-10-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('usuarios', '0002_alter_usuario_rol_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('EN_ATENCION', 'En atención'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='usuarios.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='usuarios.paciente')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.DeleteModel(
            name='CitaMedica',
        ),
    ]
